{% set name = "wily" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b63e85be5855aa3bfdd17db9b27475624539adc3bc1c8265805437ed5256a581

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=19.1
    - flit >=2.0
  run:
    - python >={{ python_min }}
    - dataclasses
    - click >=7.0,<9.0
    - colorlog >=4.0.0,<5.0
    - gitpython >=3.1.32,<4.0.0
    - nbformat >=5.1.3,<6.0
    - plotly >=4.0,<6.0
    - progress >=1.4,<2.0
    - radon >=5.1,<5.2
    - sphinx
    - sphinx-click
    - tabulate >=0.9.0,<1.0

test:
  requires:
    - pytest
    - git
    - mock
    - python {{ python_min }}
  source_files:
    - test/
  imports:
    - wily
  commands:
    - pytest test/integration -k "not test_ipynb.py"
    - wily --help

about:
  home: https://github.com/tonybaloney/wily
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A command-line application for tracking, reporting on complexity of Python tests and applications.
  description: |
    Wily uses git to go through each revision (commit) in a branch and run complexity
    and code-analysis metrics over the code. You can use this to limit your code or
    report on trends for complexity, length etc.
  doc_url: https://wily.readthedocs.io/
  dev_url: https://github.com/tonybaloney/wily

extra:
  recipe-maintainers:
    - tonybaloney
    - Zeitsperre
