{% set name = "wily" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f302d94a98f96d0f696cfbdb30d8655f5833ee564976a45289d5d46d985e2cd3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip >=19.1
    - flit >=2.0
  run:
    - python >=3.6
    - dataclasses
    - click >=7.0,<9.0
    - colorlog >=4.0.0,<5.0
    - gitpython >=3.0.0,<4.0
    - nbformat >=5.1.3,<6.0
    - plotly >=4.0,<5.0
    - progress >=1.4,<2.0
    - radon >=4.0,<4.1
    - sphinx
    - sphinx-click
    - tabulate >=0.8.2,<1.0

test:
  requires:
    - pytest
    - git
    - mock
  source_files:
    - test/
  imports:
    - wily
  commands:
    - pytest test/integration -k "not test_ipynb.py"
    - wily --help

about:
  home: https://github.com/tonybaloney/wily
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A command-line application for tracking, reporting on complexity of Python tests and applications.
  description: |
    Wily uses git to go through each revision (commit) in a branch and run complexity
    and code-analysis metrics over the code. You can use this to limit your code or
    report on trends for complexity, length etc.
  doc_url: https://wily.readthedocs.io/
  dev_url: https://github.com/tonybaloney/wily

extra:
  recipe-maintainers:
    - tonybaloney
    - Zeitsperre
